### ISSUE TITLE
TypeError: this.offsetParent is null; can't access its "getBoundingClientRect"

### ISSUE THREAD

**Issue by vincenzocalabrese** [vaadin/incubator-tooltip-flow#1]
Hello,
I've try this plugin and is very nice :-)
But, there is one problem... (I attach the console image)
![immagine](https://user-images.githubusercontent.com/30824836/47491499-3e0d3580-d84b-11e8-982f-86fdb593637f.png)

When I load the page with tooltip object into my component, I see this error (the same error is present in page). When the popup is closed, the tooltip work fine.
I've see that you have already open the issue in "incubator-tooltip" repo, but if I try to update the webjar with the fixed component (v.1.1.1), the problem is still present.

Thanks,
Vincenzo

**Comment by web-padawan** [comment]
Already fixed in web component: https://github.com/vaadin/incubator-tooltip/releases/tag/v1.1.1
The Flow counterpart has to be updated and also released to pick up that fix.
